# Generated by Django 4.2.7 on 2023-11-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
