# Generated by Django 4.2.7 on 2023-11-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_productos_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='image_url',
            field=models.CharField(max_length=400, verbose_name='Imagen'),
        ),
    ]
